# coding: utf-8

"""
    BugMark API

    all calls require BASIC AUTH  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.events_api import EventsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestEventsApi(unittest.TestCase):
    """EventsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.events_api.EventsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_events(self):
        """Test case for get_events

        Return events  # noqa: E501
        """
        pass

    def test_put_events(self):
        """Test case for put_events

        Update an event  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
